### ISSUE TITLE
Error with `net-ssh v3.2.0` : ArgumentError (wrong number of arguments calling `tcp` (5 for 4)) 

### ISSUE THREAD

**Issue by christiankakesa** [net-ssh/net-ssh-multi#20]
`net-ssh-multi v1.2.1` is not working whith `net-ssh v3.2.0` because of TCP argument error. It works with `net-ssh v2.9.2`.

###### Error output:

    error connecting to christian@localhost:22: ArgumentError (wrong number of arguments calling `tcp` (5 for 4))

**Comment by mfazekas** [comment]
What is your ruby verison? tcp have an optional 5th argument in supported rubies (2.0+)

**Comment by christiankakesa** [comment]
I'm writing a logstash plugin, JRuby 1.9 is used.

**Comment by mfazekas** [comment]
Sorry we don't support 1.9 in 3.0 or later releases:
https://github.com/net-ssh/net-ssh/tree/3-1-release#ruby-1x-support

**Comment by christiankakesa** [comment]
Yes, that's right.
